Repository XPEHO/XpeApp, pull requests merged in 2023-11, with the labels that each got.

#17 feat(newsletters): Add the newsletters page
  CHANGELOG.md
  app/build.gradle
  app/src/main/java/com/xpeho/xpeapp/data/Constants.kt
  app/src/main/java/com/xpeho/xpeapp/data/model/Newsletter.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/newsletter/NewsletterCard.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/NewsletterPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/NewsletterViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement :rocket:

#21 feat(newsletter): Add newsletter detail
  app/build.gradle
  app/src/main/java/com/xpeho/xpeapp/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/AppLoader.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/ScaffoldTemplate.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/newsletter/NewsletterCard.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/NewsletterPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/detail/NewsletterDetailComponent.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/detail/NewsletterDetailPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/NewsletterViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/detail/NewsletterDetailState.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/detail/NewsletterDetailViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement :rocket:

#19 feat(featureFlipping): Add feature flipping gesture
  app/build.gradle
  app/src/main/java/com/xpeho/xpeapp/MainActivity.kt
  app/src/main/java/com/xpeho/xpeapp/data/Constants.kt
  app/src/main/java/com/xpeho/xpeapp/data/model/FeatureFlipping.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/FeatureFlippingUiState.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/FeatureFlippingViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/theme/Color.kt
  app/src/main/java/com/xpeho/xpeapp/ui/theme/Theme.kt
  build.gradle
Labels: enhancement :rocket:

#14 feat(colleagues): Add the colleagues page
  .github/workflows/changelog.yaml
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/Button.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/colleague/HappyBirthdayComponent.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/ColleaguePage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/VacationPage.kt
  app/src/main/res/values/strings.xml
Labels: enhancement :rocket:

#23 fix(feature): Add the missing features flipping composables in home page
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/presentation/page/HomePage.kt
Labels: bug :bug:

#25 chore(ci): Use CICD workflows
  .github/workflows/android.yaml
  .github/workflows/changelog.yaml
  .github/workflows/git_checks.yaml
  .github/workflows/kotlin_analysis.yaml
  .github/workflows/labels.yaml
  CHANGELOG.md
  app/src/detekt/detekt.yaml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xpeho/xpeapp/MainActivity.kt
  app/src/main/java/com/xpeho/xpeapp/data/Constants.kt
  app/src/main/java/com/xpeho/xpeapp/data/model/FeatureFlipping.kt
  app/src/main/java/com/xpeho/xpeapp/data/model/RequestLeaveDetail.kt
  app/src/main/java/com/xpeho/xpeapp/enums/ButtonState.kt
  app/src/main/java/com/xpeho/xpeapp/enums/InputTextFieldKeyboardType.kt
  app/src/main/java/com/xpeho/xpeapp/enums/Screens.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Navigation.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/animation/ButtonAnimation.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/AppBar.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/AppLoader.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/Button.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/Card.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/InputTextField.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/ScaffoldTemplate.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/colleague/HappyBirthdayComponent.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/newsletter/NewsletterCard.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/vacation/MyRequestLeaveItem.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/vacation/MyRequestLeaveList.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/vacation/RequestStatusPicto.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/ColleaguePage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/VacationPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/NewsletterPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/detail/NewsletterDetailComponent.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/newsletter/detail/NewsletterDetailPage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/FeatureFlippingUiState.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/FeatureFlippingViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/NewsletterViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/detail/NewsletterDetailState.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/detail/NewsletterDetailViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/theme/Color.kt
  app/src/main/java/com/xpeho/xpeapp/ui/theme/Theme.kt
  app/src/main/java/com/xpeho/xpeapp/ui/theme/Type.kt
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: chore :construction_worker_man:

#32 fix(design): Fix design of multiples pages
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/data/Constants.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/componants/Card.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/FeatureFlippingViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/presentation/viewModel/newsletter/NewsletterViewModel.kt
  app/src/main/res/drawable/in_progress.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug :bug:

#15 feat(login): Init the disconnection dialog
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement :rocket:

#36 feat(auth): Add the Firebase authentification
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
Labels: enhancement :rocket:

#8 feat(notifs): Notifications
  CHANGELOG.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/xpeho/xpeapp/MainActivity.kt
  app/src/main/java/com/xpeho/xpeapp/data/DatastorePref.kt
  app/src/main/java/com/xpeho/xpeapp/data/service/MyFirebaseMessagingService.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/componants/InputTextField.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/componants/NewsletterNotification.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
  app/src/main/res/drawable/newsletter_notification.xml
  app/src/main/res/xml/network_security.xml
  build.gradle
Labels: enhancement :rocket:

#43 fix(loader): Fix the loader which was not displayed
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/componants/AppLoader.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/componants/Button.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
Labels: bug :bug:

#45 fix(gray_screen): Make not appear the gray screen
  CHANGELOG.md
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/Home.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/Navigation.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/presentation/viewModel/FeatureFlippingViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
Labels: bug :bug:

#42 chore(policy): Add privacy policy
  .gitignore
  CHANGELOG.md
  PRIVACY_POLICY.md
  app/src/main/java/com/xpeho/xpeapp/ui/Home.kt
  app/src/main/java/com/xpeho/xpeapp/ui/Navigation.kt
  app/src/main/java/com/xpeho/xpeapp/ui/Resources.kt
  app/src/main/java/com/xpeho/xpeapp/ui/animation/ButtonAnimation.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/AppBar.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/AppLoader.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/Button.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/Card.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/CustomDialog.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/InputTextField.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/NewsletterNotification.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/ScaffoldTemplate.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/colleague/HappyBirthdayComponent.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/newsletter/NewsletterCard.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/vacation/MyRequestLeaveItem.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/vacation/MyRequestLeaveList.kt
  app/src/main/java/com/xpeho/xpeapp/ui/componants/vacation/RequestStatusPicto.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/ColleaguePage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/HomePage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/LoginPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/VacationPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/newsletter/NewsletterPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/newsletter/detail/NewsletterDetailComponent.kt
  app/src/main/java/com/xpeho/xpeapp/ui/page/newsletter/detail/NewsletterDetailPage.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/FeatureFlippingUiState.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/FeatureFlippingViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/newsletter/NewsletterViewModel.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/newsletter/detail/NewsletterDetailState.kt
  app/src/main/java/com/xpeho/xpeapp/ui/viewModel/newsletter/detail/NewsletterDetailViewModel.kt
Labels: chore :construction_worker_man:
