Repository XPEHO/XpeApp, pull requests merged in 2024-12, with the labels that each got.

#195 feat(confidentiality): Add confidentiality policy in sidebar
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/layout/Sidebar.kt
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarView.swift
Labels: enhancement :rocket:

#198 Fix/readme
  README.md
  xpeapp_ios/XpeApp/README.md
Labels: bug :bug:

#196 feat(google_apple_limitation): Ensure the handle of the 403 http code to prevent access to qvst to testing account for stores
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/WordpressRepository.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/WordpressService.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/HomePage.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/qvst/QvstActiveCampaignsViewModel.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/qvst/QvstCampaignsViewModel.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/data/WordpressRepositoryTest.kt
  xpeapp_ios/XpeApp/XpeApp/Data/DataSource/Mocks/MockWordpressAPI.swift
  xpeapp_ios/XpeApp/XpeApp/Data/DataSource/WordpressAPI.swift
  xpeapp_ios/XpeApp/XpeApp/Data/DataSource/WordpressAPIHttpClient.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Repository/QvstRepositoryImpl.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Repository/UserRepositoryImpl.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Qvst/CampaignFormView.swift
  xpeapp_ios/XpeApp/sonar-project.properties
Labels: enhancement :rocket:

#199 fix(singular): Handle singular on days remaining
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/qvst/QvstCard.kt
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Qvst/CampaignCardView.swift
  xpeapp_ios/XpeApp/XpeApp/Utils.swift
Labels: bug :bug:

#201 feat(release_prod): Make a new release for prod
  xpeapp_android/app/build.gradle
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
Labels: enhancement :rocket:

#202 feat(android_local_notifications): Add local notifications on android
  xpeapp_android/app/build.gradle
  xpeapp_android/app/src/main/AndroidManifest.xml
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/MainActivity.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/XpeApp.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/DatastorePref.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/FirebaseService.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/MyFirebaseMessagingService.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/WordpressRepository.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/WordpressService.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/interceptor/AuthorizationHeaderInterceptor.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/di/AppModule.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/di/TokenProvider.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/domain/AuthenticationManager.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/Home.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/notifications/AlarmReceiver.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/notifications/AlarmScheduler.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/notifications/Notification.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/newsletter/NewslettersViewModel.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/qvst/QvstActiveCampaignsViewModel.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/qvst/QvstCampaignsViewModel.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/data/WordpressRepositoryTest.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/di/TokenProviderTest.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/domain/AuthenticationManagerTest.kt
Labels: enhancement :rocket:

#205 chore(actions/cache): bump to cache v4
  .github/workflows/sonar_android.yaml
Labels: chore :construction_worker_man:

#204 docs(c4): add c4 schema
  c4.puml
Labels: other

#210 docs(check): Ensure a good documentation for new arrivals on the project
  README.md
  xpeapp_android/README.md
  xpeapp_ios/XpeApp/README.md
Labels: other
