Repository XPEHO/XpeApp, pull requests merged in 2024-10, with the labels that each got.

#152 feat(ios_new_backend): Change links to be able to use new backend repository for local or online backend
  .github/workflows/changelog.yaml
  xpeapp_ios/XpeApp/XpeApp/Config.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/LoginPageView.swift
Labels: enhancement :rocket:

#153 chore(tests): setup android tests
  .github/workflows/android.yaml
  .github/workflows/debugAppBundle.yaml
  .github/workflows/releaseAppBundle.yaml
  .github/workflows/sonar.yaml
  xpeapp_android/.editorconfig
  xpeapp_android/.gitignore
  xpeapp_android/app/build.gradle
  xpeapp_android/app/src/maestroTest/login.yaml
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/model/AuthResult.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/data/service/WordpressRepository.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/domain/AuthenticationManager.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/LoginPage.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/viewModel/WordpressViewModel.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/domain/AnthenticationManagerTest.kt
  xpeapp_android/build.gradle
  xpeapp_android/gradle-wrapper.properties
  xpeapp_android/gradle.properties
  xpeapp_android/gradle/wrapper/gradle-wrapper.properties
  xpeapp_android/settings.gradle
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
Labels: chore :construction_worker_man:

#159 chore(testFlight): configure for Testflight beta test
  .github/workflows/codeql.yml
  .github/workflows/sonar_android.yaml
  .github/workflows/sonar_ios.yaml
  .gitignore
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
  xpeapp_ios/XpeApp/XpeApp/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  xpeapp_ios/XpeApp/XpeApp/Assets.xcassets/AppIcon.appiconset/AppIcon_1024.png
  xpeapp_ios/XpeApp/XpeApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  xpeapp_ios/XpeApp/XpeApp/Config.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarView.swift
Labels: chore :construction_worker_man:

#161 fix(ios_infinite_load): Remove infinite load on first app launch
  xpeapp_ios/XpeApp/XpeApp/ContentView.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Repository/UserRepositoryImpl.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/Shared/RouterView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarView.swift
  xpeapp_ios/XpeApp/XpeApp/XpeAppApp.swift
  xpeapp_ios/XpeApp/XpeAppTests/Repository/UserRepositoryTests.swift
Labels: bug :bug:

#165 chore(coverage): configure android coverage
  .github/workflows/sonar_android.yaml
  .github/workflows/sonar_ios.yaml
  .vscode/settings.json
  xpeapp_android/app/build.gradle
Labels: chore :construction_worker_man:

#150 feat(ios_newsletter_notification): Implement push notifications for newsletters in iOS
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  xpeapp_ios/XpeApp/XpeApp/Data/Model/NewsletterModel.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Repository/NewsletterRepositoryImpl.swift
  xpeapp_ios/XpeApp/XpeApp/Domain/Entity/NewsletterEntity.swift
  xpeapp_ios/XpeApp/XpeApp/Entitlements.plist
  xpeapp_ios/XpeApp/XpeApp/Info.plist
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Home/LastNewsletterPreviewView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Newsletter/NewsletterCardView.swift
  xpeapp_ios/XpeApp/XpeApp/XpeApp.entitlements
  xpeapp_ios/XpeApp/XpeApp/XpeAppApp.swift
  xpeapp_ios/XpeApp/XpeAppTests/ModelEntity/NewsletterModelEntityTests.swift
  xpeapp_ios/XpeApp/XpeAppTests/Repository/NewsletterRepositoryTests.swift
Labels: enhancement :rocket:

#168 chore(android_release): Make a first release with the new design (1.2.0)
  .DS_Store
  xpeapp_android/app/build.gradle
Labels: chore :construction_worker_man:
