Repository XPEHO/XpeApp, pull requests merged in 2025-01, with the labels that each got.

#212 hotfix(androidFeature): fix pop up to featureFlippingEnum
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/domain/FeatureFlippingManager.kt
  xpeapp_android/app/src/test/java/com/xpeho/xpeapp/domain/FeatureFlippingManagerTest.kt
Labels: other

#213 feat(android): new release
  xpeapp_android/app/build.gradle
Labels: enhancement :rocket:

#214 feat(analytics): Add Firebase Analytics
  xpeapp_android/app/build.gradle
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/di/AppModule.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/Resources.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/newsletter/NewsletterCard.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/HomePage.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/LoginPage.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/NewsletterPage.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/qvst/QvstCampaignDetail.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/qvst/QvstPage.kt
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Home/HomePageView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/LoginPageView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Newsletter/NewsletterCardView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Newsletter/NewsletterPageView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Qvst/CampaignsPageView.swift
  xpeapp_ios/XpeApp/XpeApp/Utils.swift
Labels: enhancement :rocket:

#211 feat(ios_sidebar): adding the profil part in sidebar
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  xpeapp_ios/XpeApp/XpeApp/Assets.xcassets/About.imageset/Contents.json
  xpeapp_ios/XpeApp/XpeApp/Assets.xcassets/About.imageset/Vector.svg
  xpeapp_ios/XpeApp/XpeApp/Data/DataSource/Mocks/MockWordpressAPI.swift
  xpeapp_ios/XpeApp/XpeApp/Data/DataSource/WordpressAPI.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Model/Login/UserPasswordEditModel.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Model/Login/UserPasswordEditResponseModel.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Model/Login/UserPasswordEditReturnEnum.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Model/User-Infos/UserInfosModel.swift
  xpeapp_ios/XpeApp/XpeApp/Data/Repository/UserRepositoryImpl.swift
  xpeapp_ios/XpeApp/XpeApp/Domain/Entity/UserInfosEntity.swift
  xpeapp_ios/XpeApp/XpeApp/Domain/Repository/UserRepository.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/Shared/LoginManager.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/Shared/RouterManager.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/Shared/RouterView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Home/HomePageView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarItemProfileView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Profile/ProfileEditPasswordView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Profile/ProfilePageView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Profile/ProfileUserInfosView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/ViewModel/UserInfosPageViewModel.swift
  xpeapp_ios/XpeApp/XpeAppTests/Repository/UserRepositoryTests.swift
Labels: enhancement :rocket:

#220 feat(app_modal_android): adding the about part in sidebar
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/Layout.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/layout/Sidebar.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/layout/SidebarItem.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/components/layout/SidebarItemProfile.kt
  xpeapp_android/app/src/main/java/com/xpeho/xpeapp/ui/page/about/AboutView.kt
  xpeapp_android/app/src/main/res/values/strings.xml
Labels: enhancement :rocket:

#219 feat(app_modal_page_ios): create app information modal page
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
  xpeapp_ios/XpeApp/XpeApp/ContentView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/Shared/RouterManager.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/About/AboutView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/ConstantsMenuItem.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarItemView.swift
  xpeapp_ios/XpeApp/XpeApp/Presentation/View/Layout/Sidebar/SidebarView.swift
  xpeapp_ios/XpeApp/sonar-project.properties
Labels: enhancement :rocket:

#221 feat(release): release swift and jetpack
  xpeapp_android/app/build.gradle
  xpeapp_ios/XpeApp/XpeApp.xcodeproj/project.pbxproj
Labels: enhancement :rocket:

#222 chore(release_workflow): Update releaseAppBundle.yaml
  .github/workflows/releaseAppBundle.yaml
Labels: chore :construction_worker_man:

#223 fix(assembleRelease): Add fragment dependency
  .github/workflows/debugAppBundle.yaml
  .github/workflows/releaseAppBundle.yaml
  xpeapp_android/app/build.gradle
Labels: bug :bug:

#224 fix(release_workflow): Automatize the release on publish new tag with the version name and code calculated
  .github/workflows/debugAppBundle.yaml
  .github/workflows/releaseAppBundle.yaml
  xpeapp_android/app/build.gradle
Labels: bug :bug:

#225 chore(sonar): add manual trigger
  .github/workflows/sonar_android.yaml
  .github/workflows/sonar_ios.yaml
Labels: chore :construction_worker_man:

#226 fix(workflows): Filter workflows execution depending code edited
  .github/workflows/android.yaml
  .github/workflows/codeql.yml
  .github/workflows/debugAppBundle.yaml
  .github/workflows/detekt.yml
Labels: bug :bug:
